FROM bitnami/minideb:jessie 

#set the working directory to where the librarian files will be stored 
WORKDIR /librarian_image

#set up the proxy information in apt.conf and etc/environment. Make sure to enter own proxy information
RUN echo "http_proxy=<http proxy>\nhttps_proxy=<https proxy>\nftp_proxy=<ftp proxy>" >> /etc/environment
RUN echo "Acquire::http::proxy \"<http proxy>\"; Acquire::https::proxy \"<https proxy>\"; Acquire::ftp::proxy \"<ftp proxy>\";" >> /etc/apt/apt.conf

#set build time variables if behind firewall. Please enter own proxy information
ARG HTTP_PROXY=http://web-proxy.corp.hpecorp.net:8080
ARG HTTPS_PROXY=http://web-proxy.corp.hpecorp.net:8080


#expose ports for TCP and internet communication
EXPOSE 9093

#install git and any other packages needed, always use the -qy option
RUN apt-get update
RUN apt-get -qy install git 
RUN apt-get -qy install python3
RUN apt-get -qy install nano 

#pull the librarian from the FAME repo --> copy the librarian data into the container 
RUN git clone https://github.com/FabricAttachedMemory/tm-librarian.git
